name: Run Tests on Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Make
      - name: Install Make
        run: sudo apt-get install make -y

      # Step 4: Run the Makefile to build, run, test, and tear down
      - name: Build, Run, Test, and Tear Down
        run: make full-test
